// Generated by Lumen compiler - ROCm/HIP Backend (AMD GPUs)
#include <hip/hip_runtime.h>
#include <hipblas.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>

// HIP error checking macro
#define HIP_CHECK(call) \
    do { \
        hipError_t err = call; \
        if (err != hipSuccess) { \
            fprintf(stderr, "HIP error at %s:%d: %s\n", __FILE__, __LINE__, hipGetErrorString(err)); \
            exit(EXIT_FAILURE); \
        } \
    } while (0)

// Tiled Matrix Multiplication Kernel
#define TILE_SIZE 32

__global__ void matmul_kernel(
    const float* __restrict__ A,
    const float* __restrict__ B,
    float* __restrict__ C,
    int M, int N, int K
) {
    // Block index
    int bx = blockIdx.x;
    int by = blockIdx.y;
    
    // Thread index
    int tx = threadIdx.x;
    int ty = threadIdx.y;
    
    // Index of the first sub-matrix of A processed by the block
    int aBegin = K * TILE_SIZE * by;
    
    // Index of the first sub-matrix of B processed by the block
    int bBegin = TILE_SIZE * bx;
    
    // Csub is used to store the element of the block sub-matrix
    float Csub = 0.0f;
    
    // Loop over all the sub-matrices of A and B
    for (int a = aBegin, b = bBegin; a <= aBegin + K - 1; a += TILE_SIZE, b += TILE_SIZE * N) {
        // Shared memory for the sub-matrices of A and B
        __shared__ float As[TILE_SIZE][TILE_SIZE];
        __shared__ float Bs[TILE_SIZE][TILE_SIZE];
        
        // Load the matrices from device memory to shared memory
        if (a / K + ty < M && a % K + tx < K)
            As[ty][tx] = A[a + K * ty + tx];
        else
            As[ty][tx] = 0.0f;
        
        if (b / N + ty < K && b % N + tx < N)
            Bs[ty][tx] = B[b + N * ty + tx];
        else
            Bs[ty][tx] = 0.0f;
        
        // Synchronize to make sure the matrices are loaded
        __syncthreads();
        
        // Multiply the two matrices together
        #pragma unroll
        for (int k = 0; k < TILE_SIZE; ++k) {
            Csub += As[ty][k] * Bs[k][tx];
        }
        
        // Synchronize to make sure computation is done
        __syncthreads();
    }
    
    // Write the block sub-matrix to device memory
    int c = N * TILE_SIZE * by + TILE_SIZE * bx;
    if (by * TILE_SIZE + ty < M && bx * TILE_SIZE + tx < N)
        C[c + N * ty + tx] = Csub;
}

// ReLU Activation Kernel
__global__ void relu_kernel(const float* __restrict__ input, float* __restrict__ output, int n) {
    int idx = blockIdx.x * blockDim.x + threadIdx.x;
    if (idx < n) {
        output[idx] = fmaxf(0.0f, input[idx]);
    }
}

// Sigmoid Activation Kernel
__global__ void sigmoid_kernel(const float* __restrict__ input, float* __restrict__ output, int n) {
    int idx = blockIdx.x * blockDim.x + threadIdx.x;
    if (idx < n) {
        output[idx] = 1.0f / (1.0f + expf(-input[idx]));
    }
}

// Tanh Activation Kernel
__global__ void tanh_kernel(const float* __restrict__ input, float* __restrict__ output, int n) {
    int idx = blockIdx.x * blockDim.x + threadIdx.x;
    if (idx < n) {
        output[idx] = tanhf(input[idx]);
    }
}

// Host wrapper for matrix multiplication
void hip_matmul(const float* A, const float* B, float* C, int M, int N, int K) {
    dim3 threads(TILE_SIZE, TILE_SIZE);
    dim3 grid((N + TILE_SIZE - 1) / TILE_SIZE, (M + TILE_SIZE - 1) / TILE_SIZE);
    
    hipLaunchKernelGGL(matmul_kernel, grid, threads, 0, 0, A, B, C, M, N, K);
    HIP_CHECK(hipDeviceSynchronize());
}

// Host wrapper for ReLU
void hip_relu(const float* input, float* output, int n) {
    int threads = 256;
    int blocks = (n + threads - 1) / threads;
    
    hipLaunchKernelGGL(relu_kernel, dim3(blocks), dim3(threads), 0, 0, input, output, n);
    HIP_CHECK(hipDeviceSynchronize());
}

// Host wrapper for Sigmoid
void hip_sigmoid(const float* input, float* output, int n) {
    int threads = 256;
    int blocks = (n + threads - 1) / threads;
    
    hipLaunchKernelGGL(sigmoid_kernel, dim3(blocks), dim3(threads), 0, 0, input, output, n);
    HIP_CHECK(hipDeviceSynchronize());
}

// Host wrapper for Tanh
void hip_tanh(const float* input, float* output, int n) {
    int threads = 256;
    int blocks = (n + threads - 1) / threads;
    
    hipLaunchKernelGGL(tanh_kernel, dim3(blocks), dim3(threads), 0, 0, input, output, n);
    HIP_CHECK(hipDeviceSynchronize());
}


// Function: mlp_forward
void mlp_forward(const float* x, const float* W1, const float* b1, const float* W2, const float* b2, float* output) {
    float* h1;
    // TODO: Allocate memory for h1
    // MatMul: x x W1 -> h1
    // hip_matmul(x, W1, h1, M, N, K);
    float* h2;
    // TODO: Allocate memory for h2
    // hip_relu(h1, h2, n_elements);
    float* out1;
    // TODO: Allocate memory for out1
    // MatMul: h2 x W2 -> out1
    // hip_matmul(h2, W2, out1, M, N, K);
    output = out1;  // Assign out1 to output
}


