#!/usr/bin/env python3
# Generated by Lumen compiler

import torch
import torch.nn as nn
import torch.nn.functional as F

def mlp_forward(x, W1, b1, W2, b2):
    h1 = torch.matmul(x, W1)
    h2 = F.relu(h1)
    out1 = torch.matmul(h2, W2)
    return out1

