#!/usr/bin/env python3
# Generated by Lumen compiler

import torch
import torch.nn as nn
import torch.nn.functional as F

def simple_forward(x, W):
    z = torch.matmul(x, W)
    a = F.relu(z)
    return a

