// CUDA C++ code generation backend

use crate::mir::*;
use crate::hir::*;
use crate::error::Result;
use std::fmt::Write;

pub struct CudaCodegen {
    output: String,
    indent_level: usize,
}

impl CudaCodegen {
    pub fn new() -> Self {
        Self {
            output: String::new(),
            indent_level: 0,
        }
    }

    pub fn generate(&mut self, mir: &MirProgram) -> Result<String> {
        // Header
        self.writeln("// Generated by Lumen compiler - CUDA/ROCm Backend");
        self.writeln("#include <cuda_runtime.h>");
        self.writeln("#include <cublas_v2.h>");
        self.writeln("#include <stdio.h>");
        self.writeln("#include <stdlib.h>");
        self.writeln("#include <math.h>");
        self.writeln("");
        self.writeln("// CUDA error checking macro");
        self.writeln("#define CUDA_CHECK(call) \\");
        self.writeln("    do { \\");
        self.writeln("        cudaError_t err = call; \\");
        self.writeln("        if (err != cudaSuccess) { \\");
        self.writeln("            fprintf(stderr, \"CUDA error at %s:%d: %s\\n\", __FILE__, __LINE__, cudaGetErrorString(err)); \\");
        self.writeln("            exit(EXIT_FAILURE); \\");
        self.writeln("        } \\");
        self.writeln("    } while (0)");
        self.writeln("");

        // Generate CUDA kernels
        self.generate_cuda_kernels();
        self.writeln("");

        // Generate models
        for model in &mir.models {
            self.generate_model(model)?;
            self.writeln("");
        }

        // Generate functions
        for func in &mir.functions {
            self.generate_function(func)?;
            self.writeln("");
        }

        Ok(self.output.clone())
    }

    fn generate_cuda_kernels(&mut self) {
        // MatMul kernel (tiled)
        self.writeln("// Tiled Matrix Multiplication Kernel");
        self.writeln("#define TILE_SIZE 32");
        self.writeln("");
        self.writeln("__global__ void matmul_kernel(");
        self.indent();
        self.writeln("const float* __restrict__ A,");
        self.writeln("const float* __restrict__ B,");
        self.writeln("float* __restrict__ C,");
        self.writeln("int M, int N, int K");
        self.dedent();
        self.writeln(") {");
        self.indent();

        self.writeln("// Block index");
        self.writeln("int bx = blockIdx.x;");
        self.writeln("int by = blockIdx.y;");
        self.writeln("");

        self.writeln("// Thread index");
        self.writeln("int tx = threadIdx.x;");
        self.writeln("int ty = threadIdx.y;");
        self.writeln("");

        self.writeln("// Index of the first sub-matrix of A processed by the block");
        self.writeln("int aBegin = K * TILE_SIZE * by;");
        self.writeln("");

        self.writeln("// Index of the first sub-matrix of B processed by the block");
        self.writeln("int bBegin = TILE_SIZE * bx;");
        self.writeln("");

        self.writeln("// Csub is used to store the element of the block sub-matrix");
        self.writeln("float Csub = 0.0f;");
        self.writeln("");

        self.writeln("// Loop over all the sub-matrices of A and B");
        self.writeln("for (int a = aBegin, b = bBegin; a <= aBegin + K - 1; a += TILE_SIZE, b += TILE_SIZE * N) {");
        self.indent();

        self.writeln("// Shared memory for the sub-matrices of A and B");
        self.writeln("__shared__ float As[TILE_SIZE][TILE_SIZE];");
        self.writeln("__shared__ float Bs[TILE_SIZE][TILE_SIZE];");
        self.writeln("");

        self.writeln("// Load the matrices from device memory to shared memory");
        self.writeln("if (a / K + ty < M && a % K + tx < K)");
        self.indent();
        self.writeln("As[ty][tx] = A[a + K * ty + tx];");
        self.dedent();
        self.writeln("else");
        self.indent();
        self.writeln("As[ty][tx] = 0.0f;");
        self.dedent();
        self.writeln("");

        self.writeln("if (b / N + ty < K && b % N + tx < N)");
        self.indent();
        self.writeln("Bs[ty][tx] = B[b + N * ty + tx];");
        self.dedent();
        self.writeln("else");
        self.indent();
        self.writeln("Bs[ty][tx] = 0.0f;");
        self.dedent();
        self.writeln("");

        self.writeln("// Synchronize to make sure the matrices are loaded");
        self.writeln("__syncthreads();");
        self.writeln("");

        self.writeln("// Multiply the two matrices together");
        self.writeln("#pragma unroll");
        self.writeln("for (int k = 0; k < TILE_SIZE; ++k) {");
        self.indent();
        self.writeln("Csub += As[ty][k] * Bs[k][tx];");
        self.dedent();
        self.writeln("}");
        self.writeln("");

        self.writeln("// Synchronize to make sure computation is done");
        self.writeln("__syncthreads();");

        self.dedent();
        self.writeln("}");
        self.writeln("");

        self.writeln("// Write the block sub-matrix to device memory");
        self.writeln("int c = N * TILE_SIZE * by + TILE_SIZE * bx;");
        self.writeln("if (by * TILE_SIZE + ty < M && bx * TILE_SIZE + tx < N)");
        self.indent();
        self.writeln("C[c + N * ty + tx] = Csub;");
        self.dedent();

        self.dedent();
        self.writeln("}");
        self.writeln("");

        // ReLU kernel
        self.writeln("// ReLU Activation Kernel");
        self.writeln("__global__ void relu_kernel(const float* __restrict__ input, float* __restrict__ output, int n) {");
        self.indent();
        self.writeln("int idx = blockIdx.x * blockDim.x + threadIdx.x;");
        self.writeln("if (idx < n) {");
        self.indent();
        self.writeln("output[idx] = fmaxf(0.0f, input[idx]);");
        self.dedent();
        self.writeln("}");
        self.dedent();
        self.writeln("}");
        self.writeln("");

        // Sigmoid kernel
        self.writeln("// Sigmoid Activation Kernel");
        self.writeln("__global__ void sigmoid_kernel(const float* __restrict__ input, float* __restrict__ output, int n) {");
        self.indent();
        self.writeln("int idx = blockIdx.x * blockDim.x + threadIdx.x;");
        self.writeln("if (idx < n) {");
        self.indent();
        self.writeln("output[idx] = 1.0f / (1.0f + expf(-input[idx]));");
        self.dedent();
        self.writeln("}");
        self.dedent();
        self.writeln("}");
        self.writeln("");

        // Tanh kernel
        self.writeln("// Tanh Activation Kernel");
        self.writeln("__global__ void tanh_kernel(const float* __restrict__ input, float* __restrict__ output, int n) {");
        self.indent();
        self.writeln("int idx = blockIdx.x * blockDim.x + threadIdx.x;");
        self.writeln("if (idx < n) {");
        self.indent();
        self.writeln("output[idx] = tanhf(input[idx]);");
        self.dedent();
        self.writeln("}");
        self.dedent();
        self.writeln("}");
        self.writeln("");

        // Host wrapper functions
        self.generate_host_wrappers();
    }

    fn generate_host_wrappers(&mut self) {
        // MatMul wrapper
        self.writeln("// Host wrapper for matrix multiplication");
        self.writeln("void cuda_matmul(const float* A, const float* B, float* C, int M, int N, int K) {");
        self.indent();
        self.writeln("dim3 threads(TILE_SIZE, TILE_SIZE);");
        self.writeln("dim3 grid((N + TILE_SIZE - 1) / TILE_SIZE, (M + TILE_SIZE - 1) / TILE_SIZE);");
        self.writeln("");
        self.writeln("matmul_kernel<<<grid, threads>>>(A, B, C, M, N, K);");
        self.writeln("CUDA_CHECK(cudaDeviceSynchronize());");
        self.dedent();
        self.writeln("}");
        self.writeln("");

        // ReLU wrapper
        self.writeln("// Host wrapper for ReLU");
        self.writeln("void cuda_relu(const float* input, float* output, int n) {");
        self.indent();
        self.writeln("int threads = 256;");
        self.writeln("int blocks = (n + threads - 1) / threads;");
        self.writeln("");
        self.writeln("relu_kernel<<<blocks, threads>>>(input, output, n);");
        self.writeln("CUDA_CHECK(cudaDeviceSynchronize());");
        self.dedent();
        self.writeln("}");
        self.writeln("");

        // Sigmoid wrapper
        self.writeln("// Host wrapper for Sigmoid");
        self.writeln("void cuda_sigmoid(const float* input, float* output, int n) {");
        self.indent();
        self.writeln("int threads = 256;");
        self.writeln("int blocks = (n + threads - 1) / threads;");
        self.writeln("");
        self.writeln("sigmoid_kernel<<<blocks, threads>>>(input, output, n);");
        self.writeln("CUDA_CHECK(cudaDeviceSynchronize());");
        self.dedent();
        self.writeln("}");
        self.writeln("");

        // Tanh wrapper
        self.writeln("// Host wrapper for Tanh");
        self.writeln("void cuda_tanh(const float* input, float* output, int n) {");
        self.indent();
        self.writeln("int threads = 256;");
        self.writeln("int blocks = (n + threads - 1) / threads;");
        self.writeln("");
        self.writeln("tanh_kernel<<<blocks, threads>>>(input, output, n);");
        self.writeln("CUDA_CHECK(cudaDeviceSynchronize());");
        self.dedent();
        self.writeln("}");
        self.writeln("");
    }

    fn generate_model(&mut self, model: &MirModel) -> Result<()> {
        self.writeln(&format!("// Model: {}", model.name));
        self.writeln(&format!("struct {} {{", model.name));
        self.indent();

        // Parameters as device pointers
        for param in &model.params {
            let shape_str = self.type_to_shape(&param.ty);
            self.writeln(&format!("float* {}; // shape: [{}]", param.name, shape_str));
        }

        self.dedent();
        self.writeln("};");
        self.writeln("");

        // Constructor
        self.writeln(&format!("void init_{}(struct {}* model) {{", model.name, model.name));
        self.indent();

        for param in &model.params {
            let size = self.calculate_size(&param.ty);
            self.writeln(&format!("CUDA_CHECK(cudaMalloc(&model->{}, {} * sizeof(float)));", param.name, size));
            self.generate_param_cuda_init(&param.name, &param.init, &size)?;
        }

        self.dedent();
        self.writeln("}");
        self.writeln("");

        // Destructor
        self.writeln(&format!("void free_{}(struct {}* model) {{", model.name, model.name));
        self.indent();

        for param in &model.params {
            self.writeln(&format!("CUDA_CHECK(cudaFree(model->{}));", param.name));
        }

        self.dedent();
        self.writeln("}");
        self.writeln("");

        Ok(())
    }

    fn generate_param_cuda_init(&mut self, name: &str, init: &HirInit, size: &str) -> Result<()> {
        match init {
            HirInit::Zeros => {
                self.writeln(&format!("CUDA_CHECK(cudaMemset(model->{}, 0, {} * sizeof(float)));", name, size));
            }
            HirInit::Ones => {
                self.writeln(&format!("// Initialize {} to ones (requires host buffer)", name));
                self.writeln(&format!("float* h_{} = (float*)malloc({} * sizeof(float));", name, size));
                self.writeln(&format!("for (int i = 0; i < {}; i++) h_{}[i] = 1.0f;", size, name));
                self.writeln(&format!("CUDA_CHECK(cudaMemcpy(model->{}, h_{}, {} * sizeof(float), cudaMemcpyHostToDevice));", name, name, size));
                self.writeln(&format!("free(h_{});", name));
            }
            HirInit::Xavier | HirInit::Kaiming => {
                self.writeln(&format!("// Initialize {} with Xavier/Kaiming (requires cuRAND)", name));
                self.writeln(&format!("// Placeholder: using zeros for now"));
                self.writeln(&format!("CUDA_CHECK(cudaMemset(model->{}, 0, {} * sizeof(float)));", name, size));
            }
            _ => {
                self.writeln(&format!("// Initialize {} (custom init not implemented)", name));
                self.writeln(&format!("CUDA_CHECK(cudaMemset(model->{}, 0, {} * sizeof(float)));", name, size));
            }
        }
        Ok(())
    }

    fn generate_function(&mut self, func: &MirFunction) -> Result<()> {
        // Generate function signature
        let params_str = func.params.iter()
            .map(|p| format!("const float* {}", p.name))
            .collect::<Vec<_>>()
            .join(", ");

        self.writeln(&format!("// Function: {}", func.name));
        self.writeln(&format!("void {}({}, float* output) {{", func.name, params_str));
        self.indent();

        // Generate function body
        if func.body.is_empty() {
            self.writeln("// Empty function body");
        } else {
            for stmt in &func.body {
                self.generate_stmt(stmt)?;
            }
        }

        self.dedent();
        self.writeln("}");
        self.writeln("");

        Ok(())
    }

    fn generate_stmt(&mut self, stmt: &MirStmt) -> Result<()> {
        match stmt {
            MirStmt::Assign { name, value, .. } => {
                // Declare device memory pointer for intermediate results
                self.writeln(&format!("float* {};", name));
                self.writeln(&format!("// TODO: Allocate memory for {}", name));

                // Generate the computation
                self.generate_expr_to_buffer(value, name)?;
            }
            MirStmt::Return { value } => {
                if let Some(expr) = value {
                    self.generate_expr_to_buffer(expr, "output")?;
                }
            }
        }

        Ok(())
    }

    fn generate_expr_to_buffer(&mut self, expr: &MirExpr, output_buf: &str) -> Result<()> {
        match expr {
            MirExpr::Var { name, .. } => {
                // Assign one buffer to another
                if name != output_buf {
                    self.writeln(&format!("{} = {};  // Assign {} to {}", output_buf, name, name, output_buf));
                }
            }
            MirExpr::Call { func, args } => {
                let args_names: Vec<String> = args.iter()
                    .filter_map(|arg| match arg {
                        MirExpr::Var { name, .. } => Some(name.clone()),
                        _ => None,
                    })
                    .collect();

                match func.as_str() {
                    "matmul" if args_names.len() == 2 => {
                        let a = &args_names[0];
                        let b = &args_names[1];
                        self.writeln(&format!("// MatMul: {} x {} -> {}", a, b, output_buf));
                        self.writeln(&format!("// cuda_matmul({}, {}, {}, M, N, K);", a, b, output_buf));
                    }
                    "relu" if args_names.len() == 1 => {
                        let input = &args_names[0];
                        self.writeln(&format!("// cuda_relu({}, {}, n_elements);", input, output_buf));
                    }
                    "sigmoid" if args_names.len() == 1 => {
                        let input = &args_names[0];
                        self.writeln(&format!("// cuda_sigmoid({}, {}, n_elements);", input, output_buf));
                    }
                    "tanh" if args_names.len() == 1 => {
                        let input = &args_names[0];
                        self.writeln(&format!("// cuda_tanh({}, {}, n_elements);", input, output_buf));
                    }
                    _ => {
                        self.writeln(&format!("// Unsupported function: {}", func));
                    }
                }
            }
            MirExpr::BinOp { op, left, right } => {
                let left_str = self.expr_to_name(left);
                let right_str = self.expr_to_name(right);
                self.writeln(&format!("// Binary operation {:?}: {} op {}", op, left_str, right_str));
            }
            _ => {
                self.writeln("// Unsupported expression");
            }
        }

        Ok(())
    }

    fn expr_to_name(&self, expr: &MirExpr) -> String {
        match expr {
            MirExpr::Var { name, .. } => name.clone(),
            _ => "<complex_expr>".to_string(),
        }
    }

    fn type_to_shape(&self, ty: &HirType) -> String {
        match ty {
            HirType::Tensor { shape, .. } => {
                shape.iter()
                    .map(|d| match d {
                        HirDimExpr::Const(c) => c.to_string(),
                        HirDimExpr::Symbolic(s) => s.clone(),
                    })
                    .collect::<Vec<_>>()
                    .join(", ")
            }
            _ => "1".to_string(),
        }
    }

    fn calculate_size(&self, ty: &HirType) -> String {
        match ty {
            HirType::Tensor { shape, .. } => {
                let dims: Vec<String> = shape.iter()
                    .map(|d| match d {
                        HirDimExpr::Const(c) => c.to_string(),
                        HirDimExpr::Symbolic(s) => s.clone(),
                    })
                    .collect();
                dims.join(" * ")
            }
            _ => "1".to_string(),
        }
    }

    fn writeln(&mut self, line: &str) {
        let indent = "    ".repeat(self.indent_level);
        writeln!(self.output, "{}{}", indent, line).unwrap();
    }

    fn indent(&mut self) {
        self.indent_level += 1;
    }

    fn dedent(&mut self) {
        if self.indent_level > 0 {
            self.indent_level -= 1;
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_cuda_codegen() {
        let program = MirProgram { models: vec![], 
            models: vec![],
            functions: vec![],
        };

        let mut codegen = CudaCodegen::new();
        let code = codegen.generate(&program).unwrap();

        assert!(code.contains("#include <cuda_runtime.h>"));
        assert!(code.contains("matmul_kernel"));
        assert!(code.contains("relu_kernel"));
    }
}
