// LLVM Backend for native code generation
// Generates LLVM IR for CPU execution without Python dependency

use crate::mir::*;
use crate::hir::*;
use crate::error::Result;
use std::fmt::Write;

pub struct LLVMCodegen {
    output: String,
    indent_level: usize,
    temp_counter: usize,
}

impl LLVMCodegen {
    pub fn new() -> Self {
        Self {
            output: String::new(),
            indent_level: 0,
            temp_counter: 0,
        }
    }

    pub fn generate(&mut self, mir: &MirProgram) -> Result<String> {
        // LLVM IR Header
        self.writeln("; Generated by Lumen compiler - LLVM Backend");
        self.writeln("; Target: native CPU execution");
        self.writeln("");

        // Type definitions
        self.write_type_definitions();

        // External function declarations (tensor runtime library)
        self.write_external_declarations();

        // Generate functions
        for func in &mir.functions {
            self.generate_function(func)?;
            self.writeln("");
        }

        Ok(self.output.clone())
    }

    fn write_type_definitions(&mut self) {
        self.writeln("; Tensor type definition");
        self.writeln("%Tensor = type { float*, i64*, i64, i64 } ; data, shape, ndim, size");
        self.writeln("");
    }

    fn write_external_declarations(&mut self) {
        self.writeln("; External tensor runtime library functions");

        // Memory management
        self.writeln("declare %Tensor* @tensor_create(i64, i64*)");
        self.writeln("declare void @tensor_free(%Tensor*)");

        // Basic operations
        self.writeln("declare %Tensor* @tensor_matmul(%Tensor*, %Tensor*)");
        self.writeln("declare %Tensor* @tensor_add(%Tensor*, %Tensor*)");
        self.writeln("declare %Tensor* @tensor_mul(%Tensor*, %Tensor*)");

        // Activations
        self.writeln("declare %Tensor* @tensor_relu(%Tensor*)");
        self.writeln("declare %Tensor* @tensor_sigmoid(%Tensor*)");
        self.writeln("declare %Tensor* @tensor_tanh(%Tensor*)");

        // Loss functions
        self.writeln("declare %Tensor* @tensor_cross_entropy(%Tensor*, %Tensor*)");
        self.writeln("declare %Tensor* @tensor_mse_loss(%Tensor*, %Tensor*)");

        self.writeln("");
    }

    fn generate_function(&mut self, func: &MirFunction) -> Result<()> {
        // Function signature
        let params_str = func.params.iter()
            .map(|p| format!("%Tensor* %{}", p.name))
            .collect::<Vec<_>>()
            .join(", ");

        self.writeln(&format!("; Function: {}", func.name));
        self.writeln(&format!("define %Tensor* @{}({}) {{", func.name, params_str));
        self.indent();

        self.writeln("entry:");
        self.indent();

        // Generate function body
        for stmt in &func.body {
            self.generate_stmt(stmt)?;
        }

        self.dedent();
        self.dedent();
        self.writeln("}");

        Ok(())
    }

    fn generate_stmt(&mut self, stmt: &MirStmt) -> Result<()> {
        match stmt {
            MirStmt::Assign { name, value, .. } => {
                let result_reg = self.generate_expr(value)?;
                self.writeln(&format!("%{} = {}", name, result_reg));
            }
            MirStmt::Return { value } => {
                if let Some(expr) = value {
                    let result_reg = self.generate_expr(expr)?;
                    self.writeln(&format!("ret %Tensor* {}", result_reg));
                } else {
                    self.writeln("ret void");
                }
            }
        }

        Ok(())
    }

    fn generate_expr(&mut self, expr: &MirExpr) -> Result<String> {
        match expr {
            MirExpr::Var { name, .. } => Ok(format!("%{}", name)),

            MirExpr::Call { func, args } => {
                let arg_regs: Vec<String> = args.iter()
                    .map(|arg| self.generate_expr(arg))
                    .collect::<Result<Vec<_>>>()?;

                let temp = self.next_temp();
                let runtime_func = match func.as_str() {
                    "matmul" => "tensor_matmul",
                    "relu" => "tensor_relu",
                    "sigmoid" => "tensor_sigmoid",
                    "tanh" => "tensor_tanh",
                    "cross_entropy" => "tensor_cross_entropy",
                    "mse_loss" => "tensor_mse_loss",
                    _ => func.as_str(),
                };

                self.writeln(&format!(
                    "{} = call %Tensor* @{}({})",
                    temp,
                    runtime_func,
                    arg_regs.join(", ")
                ));

                Ok(temp)
            }

            MirExpr::BinOp { op, left, right } => {
                let left_reg = self.generate_expr(left)?;
                let right_reg = self.generate_expr(right)?;
                let temp = self.next_temp();

                let runtime_func = match op {
                    HirBinOp::Add => "tensor_add",
                    HirBinOp::Mul => "tensor_mul",
                    HirBinOp::MatMul => "tensor_matmul",
                    _ => "tensor_binop",
                };

                self.writeln(&format!(
                    "{} = call %Tensor* @{}({}, {})",
                    temp, runtime_func, left_reg, right_reg
                ));

                Ok(temp)
            }

            _ => Ok("%null".to_string()),
        }
    }

    fn next_temp(&mut self) -> String {
        let temp = format!("%t{}", self.temp_counter);
        self.temp_counter += 1;
        temp
    }

    fn writeln(&mut self, line: &str) {
        let indent = "  ".repeat(self.indent_level);
        writeln!(self.output, "{}{}", indent, line).unwrap();
    }

    fn indent(&mut self) {
        self.indent_level += 1;
    }

    fn dedent(&mut self) {
        if self.indent_level > 0 {
            self.indent_level -= 1;
        }
    }
}

/// C++ Tensor Runtime Library Header Generation
pub struct TensorRuntimeHeader;

impl TensorRuntimeHeader {
    pub fn generate() -> String {
        r#"// Lumen Tensor Runtime Library
// Native C++ implementation for CPU execution

#ifndef LUMEN_TENSOR_RUNTIME_H
#define LUMEN_TENSOR_RUNTIME_H

#include <cstdint>
#include <vector>
#include <memory>

namespace lumen {

struct Tensor {
    float* data;
    int64_t* shape;
    int64_t ndim;
    int64_t size;

    Tensor(int64_t ndim, const int64_t* shape);
    ~Tensor();

    // Prevent copying
    Tensor(const Tensor&) = delete;
    Tensor& operator=(const Tensor&) = delete;
};

// Memory management
extern "C" Tensor* tensor_create(int64_t ndim, int64_t* shape);
extern "C" void tensor_free(Tensor* t);

// Basic operations
extern "C" Tensor* tensor_matmul(Tensor* a, Tensor* b);
extern "C" Tensor* tensor_add(Tensor* a, Tensor* b);
extern "C" Tensor* tensor_mul(Tensor* a, Tensor* b);

// Activations
extern "C" Tensor* tensor_relu(Tensor* x);
extern "C" Tensor* tensor_sigmoid(Tensor* x);
extern "C" Tensor* tensor_tanh(Tensor* x);

// Loss functions
extern "C" Tensor* tensor_cross_entropy(Tensor* logits, Tensor* targets);
extern "C" Tensor* tensor_mse_loss(Tensor* predictions, Tensor* targets);

// BLAS integration
void cblas_sgemm_wrapper(
    const float* A, const float* B, float* C,
    int M, int N, int K
);

} // namespace lumen

#endif // LUMEN_TENSOR_RUNTIME_H
"#.to_string()
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_llvm_header() {
        let header = TensorRuntimeHeader::generate();
        assert!(header.contains("extern \"C\" Tensor* tensor_create"));
        assert!(header.contains("tensor_matmul"));
    }

    #[test]
    fn test_llvm_codegen() {
        let program = MirProgram { models: vec![], 
            models: vec![],
            functions: vec![],
        };

        let mut codegen = LLVMCodegen::new();
        let code = codegen.generate(&program).unwrap();

        assert!(code.contains("declare %Tensor*"));
        assert!(code.contains("tensor_"));
    }
}
