// PyTorch code generation backend

use crate::mir::*;
use crate::hir::*;
use crate::error::Result;
use std::fmt::Write;

pub struct PyTorchCodegen {
    output: String,
    indent_level: usize,
}

impl PyTorchCodegen {
    pub fn new() -> Self {
        Self {
            output: String::new(),
            indent_level: 0,
        }
    }

    pub fn generate(&mut self, mir: &MirProgram) -> Result<String> {
        // Header
        self.writeln("#!/usr/bin/env python3");
        self.writeln("# Generated by Lumen compiler");
        self.writeln("");
        self.writeln("import torch");
        self.writeln("import torch.nn as nn");
        self.writeln("import torch.nn.functional as F");
        self.writeln("");

        // Generate models
        for model in &mir.models {
            self.generate_model(model)?;
            self.writeln("");
        }

        // Generate functions
        for func in &mir.functions {
            self.generate_function(func)?;
            self.writeln("");
        }

        Ok(self.output.clone())
    }

    fn generate_model(&mut self, model: &MirModel) -> Result<()> {
        self.writeln(&format!("class {}(nn.Module):", model.name));
        self.indent();

        // Constructor
        self.writeln("def __init__(self):");
        self.indent();
        self.writeln("super().__init__()");

        // Initialize parameters
        for param in &model.params {
            self.generate_param_init(param)?;
        }

        self.dedent();
        self.writeln("");

        // Methods
        for method in &model.methods {
            self.generate_method(method)?;
            self.writeln("");
        }

        self.dedent();

        Ok(())
    }

    fn generate_param_init(&mut self, param: &MirParam) -> Result<()> {
        let shape_str = self.type_to_shape(&param.ty);

        match &param.init {
            HirInit::Zeros => {
                self.writeln(&format!(
                    "self.{} = nn.Parameter(torch.zeros({}))",
                    param.name, shape_str
                ));
            }
            HirInit::Ones => {
                self.writeln(&format!(
                    "self.{} = nn.Parameter(torch.ones({}))",
                    param.name, shape_str
                ));
            }
            HirInit::Normal { mean, std } => {
                self.writeln(&format!(
                    "self.{} = nn.Parameter(torch.randn({}) * {} + {})",
                    param.name, shape_str, std, mean
                ));
            }
            HirInit::Uniform { low, high } => {
                self.writeln(&format!(
                    "self.{} = nn.Parameter(torch.rand({}) * ({} - {}) + {})",
                    param.name, shape_str, high, low, low
                ));
            }
            HirInit::Xavier => {
                self.writeln(&format!(
                    "self.{} = nn.Parameter(torch.empty({}))",
                    param.name, shape_str
                ));
                self.writeln(&format!(
                    "nn.init.xavier_uniform_(self.{})",
                    param.name
                ));
            }
            HirInit::Kaiming => {
                self.writeln(&format!(
                    "self.{} = nn.Parameter(torch.empty({}))",
                    param.name, shape_str
                ));
                self.writeln(&format!(
                    "nn.init.kaiming_uniform_(self.{}, nonlinearity='relu')",
                    param.name
                ));
            }
        }

        Ok(())
    }

    fn generate_method(&mut self, method: &MirFunction) -> Result<()> {
        // Method signature
        let params_str = if method.params.is_empty() {
            "self".to_string()
        } else {
            let mut params = vec!["self".to_string()];
            params.extend(method.params.iter().map(|p| p.name.clone()));
            params.join(", ")
        };

        self.writeln(&format!("def {}({}):", method.name, params_str));
        self.indent();

        // Method body
        if method.body.is_empty() {
            self.writeln("pass");
        } else {
            for stmt in &method.body {
                self.generate_stmt(stmt)?;
            }
        }

        self.dedent();

        Ok(())
    }

    fn generate_function(&mut self, func: &MirFunction) -> Result<()> {
        // Function signature
        let params_str = func.params.iter()
            .map(|p| p.name.clone())
            .collect::<Vec<_>>()
            .join(", ");

        self.writeln(&format!("def {}({}):", func.name, params_str));
        self.indent();

        // Function body
        if func.body.is_empty() {
            self.writeln("pass");
        } else {
            for stmt in &func.body {
                self.generate_stmt(stmt)?;
            }
        }

        self.dedent();

        Ok(())
    }

    fn generate_stmt(&mut self, stmt: &MirStmt) -> Result<()> {
        match stmt {
            MirStmt::Assign { name, value, .. } => {
                let value_str = self.generate_expr(value)?;
                self.writeln(&format!("{} = {}", name, value_str));
            }
            MirStmt::Return { value } => {
                if let Some(expr) = value {
                    let value_str = self.generate_expr(expr)?;
                    self.writeln(&format!("return {}", value_str));
                } else {
                    self.writeln("return");
                }
            }
        }

        Ok(())
    }

    fn generate_expr(&mut self, expr: &MirExpr) -> Result<String> {
        match expr {
            MirExpr::Var { name, .. } => Ok(name.clone()),
            MirExpr::Literal(lit) => Ok(match lit {
                HirLiteral::Int(i) => i.to_string(),
                HirLiteral::Float(f) => f.to_string(),
                HirLiteral::Bool(b) => if *b { "True" } else { "False" }.to_string(),
            }),
            MirExpr::Call { func, args } => {
                let args_str: Result<Vec<_>> = args.iter()
                    .map(|a| self.generate_expr(a))
                    .collect();
                let args_str = args_str?.join(", ");

                Ok(self.builtin_to_pytorch(func, &args_str))
            }
            MirExpr::BinOp { op, left, right } => {
                let left_str = self.generate_expr(left)?;
                let right_str = self.generate_expr(right)?;

                Ok(match op {
                    HirBinOp::Add => format!("({} + {})", left_str, right_str),
                    HirBinOp::Sub => format!("({} - {})", left_str, right_str),
                    HirBinOp::Mul => format!("({} * {})", left_str, right_str),
                    HirBinOp::Div => format!("({} / {})", left_str, right_str),
                    HirBinOp::MatMul => format!("torch.matmul({}, {})", left_str, right_str),
                })
            }
            MirExpr::UnaryOp { op, operand } => {
                let operand_str = self.generate_expr(operand)?;

                Ok(match op {
                    HirUnaryOp::Neg => format!("(-{})", operand_str),
                    HirUnaryOp::Not => format!("(not {})", operand_str),
                })
            }
            MirExpr::FieldAccess { object, field } => {
                let object_str = self.generate_expr(object)?;
                Ok(format!("{}.{}", object_str, field))
            }
        }
    }

    fn builtin_to_pytorch(&self, func: &str, args: &str) -> String {
        match func {
            "matmul" => format!("torch.matmul({})", args),
            "relu" => format!("F.relu({})", args),
            "sigmoid" => format!("torch.sigmoid({})", args),
            "tanh" => format!("torch.tanh({})", args),
            "softmax" => format!("F.softmax({}, dim=-1)", args),
            "cross_entropy" => format!("F.cross_entropy({})", args),
            "mse_loss" => format!("F.mse_loss({})", args),
            _ => format!("{}({})", func, args),
        }
    }

    fn type_to_shape(&self, ty: &HirType) -> String {
        match ty {
            HirType::Tensor { shape, .. } => {
                let dims: Vec<String> = shape.iter()
                    .map(|d| match d {
                        HirDimExpr::Const(c) => c.to_string(),
                        HirDimExpr::Symbolic(s) => s.clone(),
                    })
                    .collect();
                dims.join(", ")
            }
            _ => "1".to_string(),
        }
    }

    fn writeln(&mut self, line: &str) {
        let indent = "    ".repeat(self.indent_level);
        writeln!(self.output, "{}{}", indent, line).unwrap();
    }

    fn indent(&mut self) {
        self.indent_level += 1;
    }

    fn dedent(&mut self) {
        if self.indent_level > 0 {
            self.indent_level -= 1;
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_simple_codegen() {
        let model = MirModel {
            name: "TestModel".to_string(),
            params: vec![
                MirParam {
                    name: "weight".to_string(),
                    ty: HirType::Tensor {
                        dtype: Box::new(HirType::F32),
                        shape: vec![HirDimExpr::Const(10), HirDimExpr::Const(5)],
                    },
                    init: HirInit::Xavier,
                },
            ],
            methods: vec![],
        };

        let program = MirProgram {
            models: vec![model],
            functions: vec![],
        };

        let mut codegen = PyTorchCodegen::new();
        let code = codegen.generate(&program).unwrap();

        assert!(code.contains("class TestModel(nn.Module):"));
        assert!(code.contains("self.weight"));
        assert!(code.contains("xavier"));
    }
}
