// Triton GPU kernel code generation backend

use crate::mir::*;
use crate::hir::*;
use crate::error::Result;
use std::fmt::Write;

pub struct TritonCodegen {
    output: String,
    indent_level: usize,
    kernel_counter: usize,
}

impl TritonCodegen {
    pub fn new() -> Self {
        Self {
            output: String::new(),
            indent_level: 0,
            kernel_counter: 0,
        }
    }

    pub fn generate(&mut self, mir: &MirProgram) -> Result<String> {
        // Header
        self.writeln("#!/usr/bin/env python3");
        self.writeln("# Generated by Lumen compiler - Triton GPU Backend");
        self.writeln("");
        self.writeln("import torch");
        self.writeln("import triton");
        self.writeln("import triton.language as tl");
        self.writeln("");

        // Generate Triton kernels for operations
        self.generate_builtin_kernels();
        self.writeln("");

        // Generate models
        for model in &mir.models {
            self.generate_model(model)?;
            self.writeln("");
        }

        // Generate functions
        for func in &mir.functions {
            self.generate_function(func)?;
            self.writeln("");
        }

        Ok(self.output.clone())
    }

    fn generate_builtin_kernels(&mut self) {
        // MatMul Kernel (optimized with tiling)
        self.writeln("@triton.jit");
        self.writeln("def matmul_kernel(");
        self.indent();
        self.writeln("a_ptr, b_ptr, c_ptr,");
        self.writeln("M, N, K,");
        self.writeln("stride_am, stride_ak,");
        self.writeln("stride_bk, stride_bn,");
        self.writeln("stride_cm, stride_cn,");
        self.writeln("BLOCK_SIZE_M: tl.constexpr, BLOCK_SIZE_N: tl.constexpr, BLOCK_SIZE_K: tl.constexpr,");
        self.dedent();
        self.writeln("):");
        self.indent();

        self.writeln("# Get program ID");
        self.writeln("pid = tl.program_id(axis=0)");
        self.writeln("num_pid_m = tl.cdiv(M, BLOCK_SIZE_M)");
        self.writeln("num_pid_n = tl.cdiv(N, BLOCK_SIZE_N)");
        self.writeln("num_pid_in_group = 8");
        self.writeln("group_id = pid // (num_pid_m * num_pid_n // num_pid_in_group)");
        self.writeln("first_pid_m = (group_id * num_pid_in_group) % num_pid_m");
        self.writeln("group_size_m = min(num_pid_m - first_pid_m, num_pid_in_group)");
        self.writeln("pid_m = first_pid_m + (pid % group_size_m)");
        self.writeln("pid_n = (pid % (num_pid_m * num_pid_n // num_pid_in_group)) // group_size_m");
        self.writeln("");

        self.writeln("# Create pointers for the block");
        self.writeln("offs_am = (pid_m * BLOCK_SIZE_M + tl.arange(0, BLOCK_SIZE_M)) % M");
        self.writeln("offs_bn = (pid_n * BLOCK_SIZE_N + tl.arange(0, BLOCK_SIZE_N)) % N");
        self.writeln("offs_k = tl.arange(0, BLOCK_SIZE_K)");
        self.writeln("a_ptrs = a_ptr + (offs_am[:, None] * stride_am + offs_k[None, :] * stride_ak)");
        self.writeln("b_ptrs = b_ptr + (offs_k[:, None] * stride_bk + offs_bn[None, :] * stride_bn)");
        self.writeln("");

        self.writeln("# Iterate to compute a block of the C matrix");
        self.writeln("accumulator = tl.zeros((BLOCK_SIZE_M, BLOCK_SIZE_N), dtype=tl.float32)");
        self.writeln("for k in range(0, tl.cdiv(K, BLOCK_SIZE_K)):");
        self.indent();
        self.writeln("# Load the next block of A and B");
        self.writeln("a = tl.load(a_ptrs, mask=offs_k[None, :] < K - k * BLOCK_SIZE_K, other=0.0)");
        self.writeln("b = tl.load(b_ptrs, mask=offs_k[:, None] < K - k * BLOCK_SIZE_K, other=0.0)");
        self.writeln("# Dot product");
        self.writeln("accumulator += tl.dot(a, b)");
        self.writeln("# Advance pointers");
        self.writeln("a_ptrs += BLOCK_SIZE_K * stride_ak");
        self.writeln("b_ptrs += BLOCK_SIZE_K * stride_bk");
        self.dedent();
        self.writeln("");

        self.writeln("# Write back the block of the output matrix");
        self.writeln("c = accumulator.to(tl.float32)");
        self.writeln("offs_cm = pid_m * BLOCK_SIZE_M + tl.arange(0, BLOCK_SIZE_M)");
        self.writeln("offs_cn = pid_n * BLOCK_SIZE_N + tl.arange(0, BLOCK_SIZE_N)");
        self.writeln("c_ptrs = c_ptr + stride_cm * offs_cm[:, None] + stride_cn * offs_cn[None, :]");
        self.writeln("c_mask = (offs_cm[:, None] < M) & (offs_cn[None, :] < N)");
        self.writeln("tl.store(c_ptrs, c, mask=c_mask)");
        self.dedent();
        self.writeln("");

        // MatMul wrapper
        self.writeln("def triton_matmul(a, b):");
        self.indent();
        self.writeln("# Check constraints");
        self.writeln("assert a.shape[1] == b.shape[0], 'Incompatible dimensions'");
        self.writeln("assert a.is_contiguous(), 'Matrix A must be contiguous'");
        self.writeln("assert b.is_contiguous(), 'Matrix B must be contiguous'");
        self.writeln("M, K = a.shape");
        self.writeln("K, N = b.shape");
        self.writeln("# Allocate output");
        self.writeln("c = torch.empty((M, N), device=a.device, dtype=a.dtype)");
        self.writeln("# Launch kernel");
        self.writeln("grid = lambda META: (triton.cdiv(M, META['BLOCK_SIZE_M']) * triton.cdiv(N, META['BLOCK_SIZE_N']),)");
        self.writeln("matmul_kernel[grid](");
        self.indent();
        self.writeln("a, b, c,");
        self.writeln("M, N, K,");
        self.writeln("a.stride(0), a.stride(1),");
        self.writeln("b.stride(0), b.stride(1),");
        self.writeln("c.stride(0), c.stride(1),");
        self.writeln("BLOCK_SIZE_M=128, BLOCK_SIZE_N=128, BLOCK_SIZE_K=32,");
        self.dedent();
        self.writeln(")");
        self.writeln("return c");
        self.dedent();
        self.writeln("");

        // Element-wise kernels
        self.generate_elementwise_kernel("relu", "tl.maximum(x, 0)");
        self.generate_elementwise_kernel("sigmoid", "1.0 / (1.0 + tl.exp(-x))");
        self.generate_elementwise_kernel("tanh", "tl.tanh(x)");
    }

    fn generate_elementwise_kernel(&mut self, name: &str, operation: &str) {
        self.writeln(&format!("@triton.jit"));
        self.writeln(&format!("def {}_kernel(x_ptr, output_ptr, n_elements, BLOCK_SIZE: tl.constexpr):", name));
        self.indent();
        self.writeln("pid = tl.program_id(axis=0)");
        self.writeln("block_start = pid * BLOCK_SIZE");
        self.writeln("offsets = block_start + tl.arange(0, BLOCK_SIZE)");
        self.writeln("mask = offsets < n_elements");
        self.writeln("x = tl.load(x_ptr + offsets, mask=mask)");
        self.writeln(&format!("output = {}", operation));
        self.writeln("tl.store(output_ptr + offsets, output, mask=mask)");
        self.dedent();
        self.writeln("");

        self.writeln(&format!("def triton_{}(x):", name));
        self.indent();
        self.writeln("output = torch.empty_like(x)");
        self.writeln("n_elements = x.numel()");
        self.writeln("grid = lambda meta: (triton.cdiv(n_elements, meta['BLOCK_SIZE']),)");
        self.writeln(&format!("{}_kernel[grid](x, output, n_elements, BLOCK_SIZE=1024)", name));
        self.writeln("return output");
        self.dedent();
        self.writeln("");
    }

    fn generate_model(&mut self, model: &MirModel) -> Result<()> {
        self.writeln(&format!("class {}:", model.name));
        self.indent();

        // Constructor
        self.writeln("def __init__(self, device='cuda'):");
        self.indent();
        self.writeln("self.device = device");

        // Initialize parameters
        for param in &model.params {
            self.generate_param_init(param)?;
        }

        self.dedent();
        self.writeln("");

        // Methods
        for method in &model.methods {
            self.generate_method(method)?;
            self.writeln("");
        }

        self.dedent();

        Ok(())
    }

    fn generate_param_init(&mut self, param: &MirParam) -> Result<()> {
        let shape_str = self.type_to_shape(&param.ty);

        match &param.init {
            HirInit::Zeros => {
                self.writeln(&format!(
                    "self.{} = torch.zeros({}, device=self.device)",
                    param.name, shape_str
                ));
            }
            HirInit::Ones => {
                self.writeln(&format!(
                    "self.{} = torch.ones({}, device=self.device)",
                    param.name, shape_str
                ));
            }
            HirInit::Normal { mean, std } => {
                self.writeln(&format!(
                    "self.{} = torch.randn({}, device=self.device) * {} + {}",
                    param.name, shape_str, std, mean
                ));
            }
            HirInit::Uniform { low, high } => {
                self.writeln(&format!(
                    "self.{} = torch.rand({}, device=self.device) * ({} - {}) + {}",
                    param.name, shape_str, high, low, low
                ));
            }
            HirInit::Xavier => {
                self.writeln(&format!(
                    "self.{} = torch.empty({}, device=self.device)",
                    param.name, shape_str
                ));
                self.writeln(&format!(
                    "torch.nn.init.xavier_uniform_(self.{})",
                    param.name
                ));
            }
            HirInit::Kaiming => {
                self.writeln(&format!(
                    "self.{} = torch.empty({}, device=self.device)",
                    param.name, shape_str
                ));
                self.writeln(&format!(
                    "torch.nn.init.kaiming_uniform_(self.{}, nonlinearity='relu')",
                    param.name
                ));
            }
        }

        Ok(())
    }

    fn generate_method(&mut self, method: &MirFunction) -> Result<()> {
        let params_str = if method.params.is_empty() {
            "self".to_string()
        } else {
            let mut params = vec!["self".to_string()];
            params.extend(method.params.iter().map(|p| p.name.clone()));
            params.join(", ")
        };

        self.writeln(&format!("def {}({}):", method.name, params_str));
        self.indent();

        if method.body.is_empty() {
            self.writeln("pass");
        } else {
            for stmt in &method.body {
                self.generate_stmt(stmt)?;
            }
        }

        self.dedent();

        Ok(())
    }

    fn generate_function(&mut self, func: &MirFunction) -> Result<()> {
        let params_str = func.params.iter()
            .map(|p| p.name.clone())
            .collect::<Vec<_>>()
            .join(", ");

        self.writeln(&format!("def {}({}):", func.name, params_str));
        self.indent();

        if func.body.is_empty() {
            self.writeln("pass");
        } else {
            for stmt in &func.body {
                self.generate_stmt(stmt)?;
            }
        }

        self.dedent();

        Ok(())
    }

    fn generate_stmt(&mut self, stmt: &MirStmt) -> Result<()> {
        match stmt {
            MirStmt::Assign { name, value, .. } => {
                let value_str = self.generate_expr(value)?;
                self.writeln(&format!("{} = {}", name, value_str));
            }
            MirStmt::Return { value } => {
                if let Some(expr) = value {
                    let value_str = self.generate_expr(expr)?;
                    self.writeln(&format!("return {}", value_str));
                } else {
                    self.writeln("return");
                }
            }
        }

        Ok(())
    }

    fn generate_expr(&mut self, expr: &MirExpr) -> Result<String> {
        match expr {
            MirExpr::Var { name, .. } => Ok(name.clone()),
            MirExpr::Literal(lit) => Ok(match lit {
                HirLiteral::Int(i) => i.to_string(),
                HirLiteral::Float(f) => f.to_string(),
                HirLiteral::Bool(b) => if *b { "True" } else { "False" }.to_string(),
            }),
            MirExpr::Call { func, args } => {
                let args_str: Result<Vec<_>> = args.iter()
                    .map(|a| self.generate_expr(a))
                    .collect();
                let args_str = args_str?.join(", ");

                Ok(self.builtin_to_triton(func, &args_str))
            }
            MirExpr::BinOp { op, left, right } => {
                let left_str = self.generate_expr(left)?;
                let right_str = self.generate_expr(right)?;

                Ok(match op {
                    HirBinOp::Add => format!("({} + {})", left_str, right_str),
                    HirBinOp::Sub => format!("({} - {})", left_str, right_str),
                    HirBinOp::Mul => format!("({} * {})", left_str, right_str),
                    HirBinOp::Div => format!("({} / {})", left_str, right_str),
                    HirBinOp::MatMul => format!("triton_matmul({}, {})", left_str, right_str),
                })
            }
            MirExpr::UnaryOp { op, operand } => {
                let operand_str = self.generate_expr(operand)?;

                Ok(match op {
                    HirUnaryOp::Neg => format!("(-{})", operand_str),
                    HirUnaryOp::Not => format!("(not {})", operand_str),
                })
            }
            MirExpr::FieldAccess { object, field } => {
                let object_str = self.generate_expr(object)?;
                Ok(format!("{}.{}", object_str, field))
            }
        }
    }

    fn builtin_to_triton(&self, func: &str, args: &str) -> String {
        match func {
            "matmul" => format!("triton_matmul({})", args),
            "relu" => format!("triton_relu({})", args),
            "sigmoid" => format!("triton_sigmoid({})", args),
            "tanh" => format!("triton_tanh({})", args),
            _ => format!("{}({})", func, args),
        }
    }

    fn type_to_shape(&self, ty: &HirType) -> String {
        match ty {
            HirType::Tensor { shape, .. } => {
                let dims: Vec<String> = shape.iter()
                    .map(|d| match d {
                        HirDimExpr::Const(c) => c.to_string(),
                        HirDimExpr::Symbolic(s) => s.clone(),
                    })
                    .collect();
                dims.join(", ")
            }
            _ => "1".to_string(),
        }
    }

    fn writeln(&mut self, line: &str) {
        let indent = "    ".repeat(self.indent_level);
        writeln!(self.output, "{}{}", indent, line).unwrap();
    }

    fn indent(&mut self) {
        self.indent_level += 1;
    }

    fn dedent(&mut self) {
        if self.indent_level > 0 {
            self.indent_level -= 1;
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_triton_codegen() {
        let program = MirProgram {
            models: vec![],
            functions: vec![],
        };

        let mut codegen = TritonCodegen::new();
        let code = codegen.generate(&program).unwrap();

        assert!(code.contains("import triton"));
        assert!(code.contains("matmul_kernel"));
        assert!(code.contains("triton_matmul"));
    }
}
