// WebGPU Backend - Generate WGSL (WebGPU Shading Language) code
// For running models in web browsers

use crate::mir::*;
use crate::hir::*;
use crate::error::Result;
use std::fmt::Write;

pub struct WebGPUCodegen {
    output: String,
    indent_level: usize,
    buffer_counter: usize,
}

impl WebGPUCodegen {
    pub fn new() -> Self {
        Self {
            output: String::new(),
            indent_level: 0,
            buffer_counter: 0,
        }
    }

    pub fn generate(&mut self, mir: &MirProgram) -> Result<String> {
        self.write_header();
        self.write_buffer_definitions();
        self.write_compute_shaders(mir)?;
        self.write_javascript_runtime();

        Ok(self.output.clone())
    }

    fn write_header(&mut self) {
        self.writeln("// Generated by Lumen compiler - WebGPU Backend");
        self.writeln("// WebGPU Shading Language (WGSL) + JavaScript runtime\n");
    }

    fn write_buffer_definitions(&mut self) {
        self.writeln("// Buffer bindings");
        self.writeln("@group(0) @binding(0) var<storage, read> input: array<f32>;");
        self.writeln("@group(0) @binding(1) var<storage, read> weights: array<f32>;");
        self.writeln("@group(0) @binding(2) var<storage, read_write> output: array<f32>;\n");
    }

    fn write_compute_shaders(&mut self, mir: &MirProgram) -> Result<()> {
        for func in &mir.functions {
            self.writeln(&format!("// Compute shader for function '{}'", func.name));
            self.writeln("@compute @workgroup_size(256)");
            self.writeln(&format!("fn {}(@builtin(global_invocation_id) global_id: vec3<u32>) {{", func.name));
            self.indent();

            self.writeln("let idx = global_id.x;");

            for stmt in &func.body {
                self.generate_stmt(stmt)?;
            }

            self.dedent();
            self.writeln("}\n");
        }

        Ok(())
    }

    fn generate_stmt(&mut self, stmt: &MirStmt) -> Result<()> {
        match stmt {
            MirStmt::Assign { name, value, .. } => {
                let expr_code = self.generate_expr(value)?;
                self.writeln(&format!("let {}: f32 = {};", name, expr_code));
            }
            MirStmt::Return { value } => {
                if let Some(v) = value {
                    let expr_code = self.generate_expr(v)?;
                    self.writeln(&format!("output[idx] = {};", expr_code));
                }
            }
        }
        Ok(())
    }

    fn generate_expr(&mut self, expr: &MirExpr) -> Result<String> {
        match expr {
            MirExpr::Literal(lit) => {
                match lit {
                    crate::hir::HirLiteral::Int(v) => Ok(format!("{}f", v)),
                    crate::hir::HirLiteral::Float(v) => Ok(format!("{}f", v)),
                    crate::hir::HirLiteral::Bool(b) => Ok(if *b { "true" } else { "false" }.to_string()),
                    _ => Ok("0.0f".to_string()),
                }
            }
            MirExpr::Var { name, .. } => Ok(name.clone()),
            MirExpr::Call { func, args } => {
                match func.as_str() {
                    "matmul" => Ok("/* matmul */0.0f".to_string()),
                    "relu" => {
                        if args.len() > 0 {
                            let arg = self.generate_expr(&args[0])?;
                            Ok(format!("max({}, 0.0f)", arg))
                        } else {
                            Ok("0.0f".to_string())
                        }
                    }
                    "sigmoid" => {
                        if args.len() > 0 {
                            let arg = self.generate_expr(&args[0])?;
                            Ok(format!("1.0f / (1.0f + exp(-{}))", arg))
                        } else {
                            Ok("0.0f".to_string())
                        }
                    }
                    "tanh" => {
                        if args.len() > 0 {
                            let arg = self.generate_expr(&args[0])?;
                            Ok(format!("tanh({})", arg))
                        } else {
                            Ok("0.0f".to_string())
                        }
                    }
                    _ => Ok(format!("{}()", func)),
                }
            }
            MirExpr::BinOp { op, left, right } => {
                let left_code = self.generate_expr(left)?;
                let right_code = self.generate_expr(right)?;

                let op_str = match op {
                    HirBinOp::Add => "+",
                    HirBinOp::Sub => "-",
                    HirBinOp::Mul => "*",
                    HirBinOp::Div => "/",
                    HirBinOp::MatMul => "*", // Simplified
                };

                Ok(format!("({} {} {})", left_code, op_str, right_code))
            }
            _ => Ok("0.0f".to_string()),
        }
    }

    fn write_javascript_runtime(&mut self) {
        self.writeln("\n// JavaScript runtime");
        self.writeln("/*");
        self.writeln("const device = await navigator.gpu.requestAdapter()");
        self.writeln("  .then(adapter => adapter.requestDevice());");
        self.writeln("");
        self.writeln("// Create shader module");
        self.writeln("const shaderModule = device.createShaderModule({");
        self.writeln("  code: wgslCode,  // The WGSL code above");
        self.writeln("});");
        self.writeln("");
        self.writeln("// Create buffers");
        self.writeln("const inputBuffer = device.createBuffer({");
        self.writeln("  size: inputData.byteLength,");
        self.writeln("  usage: GPUBufferUsage.STORAGE | GPUBufferUsage.COPY_DST,");
        self.writeln("});");
        self.writeln("");
        self.writeln("const outputBuffer = device.createBuffer({");
        self.writeln("  size: outputSize,");
        self.writeln("  usage: GPUBufferUsage.STORAGE | GPUBufferUsage.COPY_SRC,");
        self.writeln("});");
        self.writeln("");
        self.writeln("// Create compute pipeline");
        self.writeln("const pipeline = device.createComputePipeline({");
        self.writeln("  layout: 'auto',");
        self.writeln("  compute: {");
        self.writeln("    module: shaderModule,");
        self.writeln("    entryPoint: 'main',");
        self.writeln("  },");
        self.writeln("});");
        self.writeln("");
        self.writeln("// Create bind group");
        self.writeln("const bindGroup = device.createBindGroup({");
        self.writeln("  layout: pipeline.getBindGroupLayout(0),");
        self.writeln("  entries: [");
        self.writeln("    { binding: 0, resource: { buffer: inputBuffer } },");
        self.writeln("    { binding: 1, resource: { buffer: weightsBuffer } },");
        self.writeln("    { binding: 2, resource: { buffer: outputBuffer } },");
        self.writeln("  ],");
        self.writeln("});");
        self.writeln("");
        self.writeln("// Dispatch compute");
        self.writeln("const commandEncoder = device.createCommandEncoder();");
        self.writeln("const passEncoder = commandEncoder.beginComputePass();");
        self.writeln("passEncoder.setPipeline(pipeline);");
        self.writeln("passEncoder.setBindGroup(0, bindGroup);");
        self.writeln("passEncoder.dispatchWorkgroups(Math.ceil(size / 256));");
        self.writeln("passEncoder.end();");
        self.writeln("");
        self.writeln("device.queue.submit([commandEncoder.finish()]);");
        self.writeln("*/");
    }

    fn writeln(&mut self, line: &str) {
        for _ in 0..self.indent_level {
            write!(self.output, "    ").unwrap();
        }
        writeln!(self.output, "{}", line).unwrap();
    }

    fn indent(&mut self) {
        self.indent_level += 1;
    }

    fn dedent(&mut self) {
        if self.indent_level > 0 {
            self.indent_level -= 1;
        }
    }
}

/// WebGPU-specific optimizations
pub struct WebGPUOptimizer {
    workgroup_size: usize,
}

impl WebGPUOptimizer {
    pub fn new() -> Self {
        Self {
            workgroup_size: 256,
        }
    }

    /// Optimize workgroup size for hardware
    pub fn optimize_workgroup_size(&mut self, total_work: usize) {
        // Common WebGPU workgroup sizes: 64, 128, 256
        if total_work < 128 {
            self.workgroup_size = 64;
        } else if total_work < 512 {
            self.workgroup_size = 128;
        } else {
            self.workgroup_size = 256;
        }
    }

    /// Generate optimized matrix multiplication kernel
    pub fn generate_optimized_matmul(&self, m: usize, n: usize, k: usize) -> String {
        format!(r#"
// Optimized WebGPU matrix multiplication
@group(0) @binding(0) var<storage, read> A: array<f32>;
@group(0) @binding(1) var<storage, read> B: array<f32>;
@group(0) @binding(2) var<storage, read_write> C: array<f32>;

const TILE_SIZE: u32 = 16u;

@compute @workgroup_size(TILE_SIZE, TILE_SIZE)
fn matmul_tiled(@builtin(global_invocation_id) global_id: vec3<u32>) {{
    let row = global_id.x;
    let col = global_id.y;

    if (row >= {}u || col >= {}u) {{
        return;
    }}

    var sum: f32 = 0.0f;

    // Tiled computation
    for (var tile = 0u; tile < {}u; tile = tile + TILE_SIZE) {{
        for (var k = 0u; k < TILE_SIZE; k = k + 1u) {{
            let a_idx = row * {}u + tile + k;
            let b_idx = (tile + k) * {}u + col;
            sum = sum + A[a_idx] * B[b_idx];
        }}
    }}

    C[row * {}u + col] = sum;
}}
"#, m, n, k, k, n, n)
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_webgpu_codegen_basic() {
        let mut codegen = WebGPUCodegen::new();
        let program = MirProgram { models: vec![], 
            functions: vec![MirFunction {
                name: "forward".to_string(),
                params: vec![],
                return_type: "void".to_string(),
                body: vec![],
            }],
        };

        let result = codegen.generate(&program);
        assert!(result.is_ok());
        assert!(result.unwrap().contains("WebGPU"));
    }

    #[test]
    fn test_workgroup_optimization() {
        let mut optimizer = WebGPUOptimizer::new();
        optimizer.optimize_workgroup_size(100);
        assert_eq!(optimizer.workgroup_size, 64);

        optimizer.optimize_workgroup_size(1000);
        assert_eq!(optimizer.workgroup_size, 256);
    }
}